TIME: 2025-08-24T17:01:03.708657+00:00
SCRIPT: s1_login
STEP: login_and_save

TRACEBACK:
Traceback (most recent call last):
  File "C:\Repo\auto_job_finder\src\s1_login_save.py", line 36, in main
    raise RuntimeError("Login not completed in time.")
RuntimeError: Login not completed in time.

